-- Enable Row Level Security (RLS) is recommended, but for simplicity we start with tables.
-- You can run this in the Supabase SQL Editor.

-- 1. Flash Tattoos
create table if not exists public.flash_tattoos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  categories text[] default '{}'::text[],
  size text,
  color text,
  price integer,
  original_price integer,
  discount integer default 0,
  description text,
  images text[] default '{}'::text[],
  status text default 'active',
  views integer default 0,
  duration integer default 60 -- Duration in minutes
);

-- 2. Gallery Items
create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  images text[] default '{}'::text[],
  categories text[] default '{}'::text[],
  status text default 'active',
  views integer default 0,
  description text
);

-- 3. Bookings
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  email text,
  booking_date date,
  booking_time time,
  project_type text,
  description text,
  status text default 'pending',
  notes text,
  reference_image text,
  booking_end_time time,
  size text,
  placement text,
  budget text,
  processed_for_gallery boolean default false
);

-- 4. Booking Exceptions (for blocking slots and events)
create table if not exists public.booking_exceptions (
  id bigint generated by default as identity primary key,
  exception_date date not null,
  exception_time time not null,
  status text not null, -- 'blocked' or 'available'
  title text,
  description text
);

-- 5. Messages
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  from_name text,
  email text,
  phone text,
  subject text,
  message_body text,
  is_read boolean default false
);

-- 6. Blog Posts
create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  publish_date date,
  status text default 'draft', -- 'published', 'draft', 'archived'
  views integer default 0
);

-- Enable RLS (Optional but good practice)
alter table public.flash_tattoos enable row level security;
alter table public.gallery_items enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_exceptions enable row level security;
alter table public.messages enable row level security;
alter table public.blog_posts enable row level security;

-- Create policies (open for now for ease of development, secure later)
-- We drop them first to avoid "policy already exists" errors when re-running
drop policy if exists "Allow public read access on flash_tattoos" on public.flash_tattoos;
create policy "Allow public read access on flash_tattoos" on public.flash_tattoos for select using (true);

drop policy if exists "Allow public read access on gallery_items" on public.gallery_items;
create policy "Allow public read access on gallery_items" on public.gallery_items for select using (true);

drop policy if exists "Allow public read access on blog_posts" on public.blog_posts;
create policy "Allow public read access on blog_posts" on public.blog_posts for select using (true);

drop policy if exists "Allow public read access on booking_exceptions" on public.booking_exceptions;
create policy "Allow public read access on booking_exceptions" on public.booking_exceptions for select using (true);

-- WRITE: Allow authenticated (service_role or generic) write - in real app, restrict to admin
drop policy if exists "Allow anon insert on bookings" on public.bookings;
create policy "Allow anon insert on bookings" on public.bookings for insert with check (true);

drop policy if exists "Allow anon insert on messages" on public.messages;
create policy "Allow anon insert on messages" on public.messages for insert with check (true);

-- For Admin parts (Flash, Blog, etc), we allow all access for demo ease
drop policy if exists "Enable all access for all users" on public.flash_tattoos;
create policy "Enable all access for all users" on public.flash_tattoos for all using (true);

drop policy if exists "Enable all access for all users" on public.gallery_items;
create policy "Enable all access for all users" on public.gallery_items for all using (true);

drop policy if exists "Enable all access for all users" on public.bookings;
create policy "Enable all access for all users" on public.bookings for all using (true);

drop policy if exists "Enable all access for all users" on public.booking_exceptions;
create policy "Enable all access for all users" on public.booking_exceptions for all using (true) with check (true);

drop policy if exists "Enable all access for all users" on public.messages;
create policy "Enable all access for all users" on public.messages for all using (true);

drop policy if exists "Enable all access for all users" on public.blog_posts;
create policy "Enable all access for all users" on public.blog_posts for all using (true);

-- 7. Banners (Carousel)
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  title text,
  description text,
  button_text text,
  button_link text,
  display_order integer default 0,
  active boolean default true
);

alter table public.banners enable row level security;
drop policy if exists "Enable all access for all users" on public.banners;
create policy "Enable all access for all users" on public.banners for all using (true);

-- 8. Promotions
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  discount_percent integer not null,
  start_date date,
  end_date date,
  active boolean default false,
  is_global boolean default true,
  target_flashes text[] default '{}'::text[]
);

alter table public.promotions enable row level security;
drop policy if exists "Enable all access for all users" on public.promotions;
create policy "Enable all access for all users" on public.promotions for all using (true);

-- 9. Admin Profiles (for User Management display)
create table if not exists public.profiles (
  id uuid default gen_random_uuid(),
  email text not null,
  role text default 'admin', -- 'admin', 'custom'
  permissions jsonb default '{}'::jsonb, -- NEW: For granular permissions
  avatar_url text, -- NEW: For profile picture
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (id)
);

alter table public.profiles enable row level security;
drop policy if exists "Enable all access for all users" on public.profiles;
create policy "Enable all access for all users" on public.profiles for all using (true);

-- 10. Increment View Functions
create or replace function increment_flash_view(row_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.flash_tattoos
  set views = coalesce(views, 0) + 1
  where id = row_id;
end;
$$;

create or replace function increment_gallery_view(row_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.gallery_items
  set views = coalesce(views, 0) + 1
  where id = row_id;
end;
$$;

-- 11. Admin Sticky Notes
create table if not exists public.admin_notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  content text,
  color text default 'bg-yellow-200',
  is_done boolean default false,
  display_order integer default 0,
  event_date date
);

alter table public.admin_notes enable row level security;
drop policy if exists "Enable all access for all users" on public.admin_notes;
create policy "Enable all access for all users" on public.admin_notes for all using (true);

-- 12. Logs (NEW)
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  action_type text not null, -- 'create', 'update', 'delete', 'auth_login', 'auth_logout'
  table_name text,
  record_id text,
  user_id uuid, -- Link to profiles/auth.users if available
  details jsonb, -- Store detailed changes or context
  status text default 'success' -- 'success', 'error'
);

alter table public.logs enable row level security;
drop policy if exists "Enable all access for all users" on public.logs;
create policy "Enable all access for all users" on public.logs for all using (true);

-- 13. Clients (NEW)
-- Assuming we might use Supabase Auth for clients too, but keeping a separate profile table for them
create table if not exists public.clients (
  id uuid default gen_random_uuid() primary key,
  email text not null unique,
  phone text,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.clients enable row level security;
drop policy if exists "Enable all access for all users" on public.clients;
create policy "Enable all access for all users" on public.clients for all using (true);

-- 14. Wishlists (NEW)
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  flash_id bigint not null references public.flash_tattoos(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(client_id, flash_id)
);

alter table public.wishlists enable row level security;
drop policy if exists "Enable all access for all users" on public.wishlists;
create policy "Enable all access for all users" on public.wishlists for all using (true);
